[FEAT] Subscribe 관련 기능 개발
SSUDevelog/EasyVel-Server pull request #8
Opened 2023-08-17 16:20 UTC by k0000k

## Issue

- Resolves #2 

## Description

- 현재 구현체가 없는 tag, notification, jwt 관련 기능은 모두 주석 처리, 임시 값 처리해둔 상태입니다.
- 리팩하면서 global dto나 코딩 컨벤션, URI 네이밍 등등... 논의할 사항들이 꽤 많이 생겨서 제가 따로 정리해두었습니다. 다음 전체 파트 회의 전에 이야기 나누어서 정한 다음에 리팩 완성하도록 하겠습니다.

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot
- 필요한 경우에만 넣어주세요.

2023-08-20 07:53 UTC, sung-silver requested changes
개인적으로 NPE가 발생할 위험성이 적어야한다고 생각해서 Repository에서 반환 타입을 리스트가 아닌 경우를 제외하고 단일 객체일 때는 Optional을 붙이는게 좋아보입니다..!

2023-08-20 07:53 UTC, sung-silver commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +    }
위에 선언된 레포지토리들 private final로 선언하고 SubsrcibeService위에 @RequiredArgsConstructor 어노테이션 붙이는건 어떨까요?

2023-08-20 07:53 UTC, sung-silver commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +        }
SubscribeService에서 사용하는 private한 함수로 빼는건 어떠실까요? 하나의 함수 안에 내용이 너무 길어 가독성을 위해 분리하는건 어떨지 제안드립니다!

2023-08-20 07:53 UTC, sung-silver commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +        }
이부분도 posts를 인자로 받는 private 함수로 빼는건 어떨까요?

2023-08-20 07:53 UTC, sung-silver commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +        }
target이 Null인 경우에 대해서 작성하기보다 Repository단에서 Optional로 반환하고 OrElse구문을 사용하여 구현하는 것은 어떨까요?

2023-08-20 07:53 UTC, sung-silver commented on src/main/java/com/easyvel/server/global/repository/NoticeTargetRepository.java
> +    NoticeTarget getByGroupName(String groupName);
Optional<NoticeTarget>으로 반환하는 건 어떨까요?

2023-08-20 10:12 UTC, kikuke commented on src/main/java/com/easyvel/server/subscribe/SubscribeController.java
> +            throw new RuntimeException(e);
exception을 변환해서 던지는 이유가 궁금합니다!

2023-08-20 10:15 UTC, kikuke commented on src/main/java/com/easyvel/server/subscribe/SubscribeController.java
> +    public ResponseEntity<List<VelogUserInfoDto>> getSubscriber(@RequestHeader("X-AUTH-TOKEN") String token) throws IOException {//제네릭 안의 제네릭 -> 별도응답 객체를 만들어야함!
List형태의 반환, dto 형태 반환 어떤 편이 좋을지 회의 때 이야기해보고 싶습니다. @RequestHeader의 X-AUTH-TOKEN 부분은 이번 리팩토링 때 상수화 시켜놔서 이후 그걸 적용하면 좋을 것 같습니다!

2023-08-20 10:17 UTC, kikuke commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +        }
해당 부분도 메서드 추출하는 것이 좋을 것 같습니다!

2023-08-20 10:19 UTC, kikuke reviewed
고생하셨습니다!

2023-08-20 11:19 UTC, sung-silver commented on src/main/java/com/easyvel/server/subscribe/SubscribeController.java
> +    public ResponseEntity<List<VelogUserInfoDto>> getSubscriber(@RequestHeader("X-AUTH-TOKEN") String token) throws IOException {//제네릭 안의 제네릭 -> 별도응답 객체를 만들어야함!
이 부분에 대해서 Mapper 적용은 어떠실까요?! 그럼 리스트로 반환후에 DTO로 손쉽게 다시 바꿀 수 있습니다!

2023-08-22 12:10 UTC, k0000k commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +    }
넵 반영하겠습니다!

2023-08-22 12:12 UTC, k0000k commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +    }
넵 반영하고 기존에 직접 생성해둔 생성자는 삭제하겠습니다.

2023-08-22 12:13 UTC, k0000k commented on src/main/java/com/easyvel/server/subscribe/SubscribeController.java
> +            throw new RuntimeException(e);
저 부분은 미처 확인하지 못했네요! 수정하겠습니다.

2023-08-22 12:25 UTC, k0000k commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +        }
반영하겠습니다!

2023-08-22 12:40 UTC, k0000k commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +        }
해당 부분은 이미 private 메소드이며, 한 가지 테스크만을 하고있다고 생각하여 더 분리할필요는 없을 것 같다고 생각합니다!

2023-08-22 13:12 UTC, k0000k commented on src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
> +        }
저 경우에는 새 Target을 생성해야 하므로, OrElseGet 사용했습니다. 추가로 리포지토리단에서 바로 Optional 던지도록 수정했습니다!

2023-08-22 13:13 UTC, k0000k commented on src/main/java/com/easyvel/server/global/repository/NoticeTargetRepository.java
> +    NoticeTarget getByGroupName(String groupName);
수정했습니다 :)

2023-08-22 13:29 UTC, k0000k commented
리포지토리도 단일 객체 리턴하는 경우 모두 Optional 처리 했습니다.

2023-08-22 13:29 UTC, k0000k commented
@kikuke @sung-silver 코멘트 달아주신 부분들 모두 반영했고, 재리뷰 요청 드렸습니다 :)

2023-08-23 12:12 UTC, sung-silver approved these changes
고생 많으셨습니다~

2023-08-23 12:12 UTC, sung-silver commented on src/main/java/com/easyvel/server/global/dto/PostDto.java
> +                System.out.println("compareDate: " + o1 + o2);
print문보다는 꼭 필요한 정보라면 log로 남기는게 좋아보입니다!

2023-08-25 07:07 UTC, kikuke approved these changes

2023-08-31 07:58 UTC, merged